// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfBAL_-Iz_US3R7g2rzSGi4FNuj1v5sg',
    appId: '1:458361446708:web:253e197c98578349354561',
    messagingSenderId: '458361446708',
    projectId: 'surveybookingapp',
    authDomain: 'surveybookingapp.firebaseapp.com',
    storageBucket: 'surveybookingapp.firebasestorage.app',
    measurementId: 'G-6QNH5P6V6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ZwbRFdD-22oFP7eviwsPMBALeUC1978',
    appId: '1:458361446708:android:62d6b42068c28c1e354561',
    messagingSenderId: '458361446708',
    projectId: 'surveybookingapp',
    storageBucket: 'surveybookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV9p_QuTg93EA99vuxsBjKERWZ-zImIKY',
    appId: '1:458361446708:ios:0afa346eaff5a4ad354561',
    messagingSenderId: '458361446708',
    projectId: 'surveybookingapp',
    storageBucket: 'surveybookingapp.firebasestorage.app',
    iosBundleId: 'com.sensrs.surveydesk',
  );
}
